version: '3'

services:
  redis:
    image: redis:alpine
  worker:
    build: .
    command: bash -c "cd example && python3 worker.py"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/code
    depends_on:
      - redis
  client:
    build: .
    command: bash -c "cd example && python3 client.py"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/code
    depends_on:
      - redis
